### Site Settings ###
title               : Andrew Saeman Consulting
description         : >-
                      Helping teams, leaders, and organizations deliver the value their customers desire.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : asaeman/ConsultingWebsite     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : asaeman/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Andrew Saeman
  image             : ../assets/img/achievement-agreement-arms-asian.jpg
# behance           : your_username
# dribbble          : your_username
  email             : andrew@andrewsaeman.com
#  facebook          : your_username
#  github            : your_username
# gitlab            : your_username
# instagram         : your_username
  linkedin          : asaeman
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : asaeman
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Defaults for collections ###
defaults:
  - scope:
      path: "assets/img"
      type: "projects"
    values:
      layout: "page"
      image: true

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"

theme: jekyll-theme-cayman